"""
Abstract Syntax Tree (AST) Definitions

Defines all statement types in Gulf of Mexico's syntax tree.
Each statement class represents a distinct language construct.

Statement Types:
    - FunctionDefinition: function/async definitions with flexible keyword matching
    - ClassDeclaration: class definitions with instance namespaces
    - VariableDeclaration: const/var declarations with confidence and lifetime
    - VariableAssignment: assignment with optional indexing
    - Conditional: if statements with expression evaluation
    - WhenStatement: reactive when triggers on variable changes
    - AfterStatement: scheduled execution with temporal delays
    - ReturnStatement: function returns with optional debug
    - DeleteStatement: value deletion from memory
    - ReverseStatement: reverse string/list/time (special operator)
    - ExpressionStatement: standalone expressions
    - ExportStatement: export values to other file sections
    - ImportStatement: import from file sections or external files

Key Features:
    - Debug levels (0-4): increasing verbosity for troubleshooting
    - Confidence levels: !, !! , !!! for variable priority
    - Type annotations: optional type hints after colons
    - Lifetimes: <5.0> for temporal, 100 for line-based

These AST nodes are generated by generate_syntax_tree() in this module,
then executed by pattern matching in interpreter.py.
"""

from abc import ABCMeta
from dataclasses import dataclass
from typing import Optional, Union

from gulfofmexico.base import (
    STR_TO_OPERATOR,
    Token,
    TokenType,
    raise_error_at_line,
    raise_error_at_token,
)
from gulfofmexico.processor.expression_tree import (
    ExpressionTreeNode,
)

__all__ = [
    "FunctionDefinition",
    "ClassDeclaration",
    "VariableDeclaration",
    "VariableAssignment",
    "Conditional",
    "ReturnStatement",
    "DeleteStatement",
    "ReverseStatement",
    "ExpressionStatement",
    "WhenStatement",
    "AfterStatement",
    "ExportStatement",
    "ImportStatement",
]


class CodeStatement:
    """Base class for all statement types."""


class CodeStatementKeywordable(metaclass=ABCMeta):
    """Statements that have a keyword token (if, when, class, etc.)."""

    keyword: Token


class CodeStatementDebuggable(metaclass=ABCMeta):
    """Statements that support debug levels (0-4 question marks)."""

    debug: int


@dataclass
class FunctionDefinition(CodeStatement):
    """Function or async function definition.

    Supports flexible keyword matching: f, fn, func, functi, function
    with optional async prefix.

    Examples:
        fn add(a, b) => a + b!
        async function process(data) => {...}!
    """

    keywords: list[Token]  # ['async', 'function'] or just ['function']
    name: Token
    args: list[Token]
    code: list[tuple[CodeStatement, ...]]
    is_async: bool


@dataclass
class ClassDeclaration(CodeStatement, CodeStatementKeywordable):
    """Class definition with instance namespace.

    Creates objects with their own variable scope. Instances
    can access class properties via dot notation.
    """

    keyword: Token
    name: Token
    code: list[tuple[CodeStatement, ...]]

    # Compatibility init for legacy tests

    def __init__(self, keyword=None, name=None, code=None):
        self.keyword = keyword
        self.name = name
        self.code = code or []


@dataclass
class VariableDeclaration(CodeStatement, CodeStatementDebuggable):
    """Variable declaration with modifiers, type, and lifetime.

    Modifiers: const, var (can combine as const var)
    Type annotation: optional after colon
    Lifetime: <5.0> for temporal, 100 for line-based
    Confidence: ! count determines priority (1-3)

    Examples:
        const x = 10!
        var y: Int <5.0> = 20!!
        const const const PI = 3.14!  (immutable global)
    """

    name: Token
    modifiers: list[Token]  # ['const'], ['var'], or ['const', 'var']
    type_annotation: Optional[list[Token]]  # Type annotation tokens (Int, String, etc.)
    lifetime: Optional[str]  # "<5.0>" or "100" or None
    expression: Union[list[Token], ExpressionTreeNode]
    debug: int  # 0-4 (number of ? marks)
    confidence: int  # 1-3 (number of ! marks)
    destructure_names: Optional[list[Token]]  # For [a, b] = expr! destructuring

    # Compatibility init for legacy tests
    def __init__(
        self,
        name=None,
        modifiers=None,
        type_annotation=None,
        lifetime=None,
        expression=None,
        debug=0,
        confidence=0,
        destructure_names=None,
    ):
        self.name = name
        self.modifiers = modifiers or []
        self.type_annotation = type_annotation
        self.lifetime = lifetime
        self.expression = expression
        self.debug = debug
        self.confidence = confidence
        self.destructure_names = destructure_names


@dataclass
class VariableAssignment(CodeStatement, CodeStatementDebuggable):
    """Variable reassignment with optional indexing.

    Supports single or multi-dimensional indexing including
    fractional indexes for insertion.

    Examples:
        x = 5!
        list[-1] = 10!
        list[0.5] = 99!  (inserts between 0 and 1)
    """

    name: Token
    expression: Union[list[Token], ExpressionTreeNode]
    debug: int
    indexes: Union[list[list[Token]], list[ExpressionTreeNode]]
    confidence: int


@dataclass
class Conditional(CodeStatement, CodeStatementKeywordable):
    """If statement with expression condition.

    Condition evaluated for boolean value (true/false/maybe).
    Maybe values handled probabilistically.
    """

    keyword: Token
    expression: Union[list[Token], ExpressionTreeNode]
    code: list[tuple[CodeStatement, ...]]


# name expression !?
@dataclass
class ReturnStatement(CodeStatement, CodeStatementDebuggable):
    keyword: Optional[Token]
    expression: Union[list[Token], ExpressionTreeNode]
    debug: int

    # Compatibility init for legacy tests constructing with minimal args

    def __init__(self, keyword=None, expression=None, debug=0):
        self.keyword = keyword
        self.expression = expression
        self.debug = debug


# name name !?
@dataclass
class DeleteStatement(CodeStatement, CodeStatementKeywordable, CodeStatementDebuggable):
    keyword: Token
    name: Token
    debug: int

    # Compatibility init for legacy tests

    def __init__(self, keyword=None, name=None, debug=0):
        self.keyword = keyword
        self.name = name
        self.debug = debug


# reverse name!
@dataclass
class ReverseStatement(CodeStatement, CodeStatementKeywordable, CodeStatementDebuggable):
    keyword: Token  # The 'reverse' keyword token
    name: Token  # The variable to reverse
    debug: int

    # Compatibility init for legacy tests

    def __init__(self, keyword=None, name=None, debug=0):
        self.keyword = keyword
        self.name = name
        self.debug = debug


# expression !?   < virtually indistinguishable from a return statement from a parsing perspective
@dataclass
class ExpressionStatement(CodeStatement, CodeStatementDebuggable):
    expression: Union[list[Token], ExpressionTreeNode]
    debug: int


# name name = expression {
@dataclass
class WhenStatement(CodeStatement, CodeStatementKeywordable):
    keyword: Token
    expression: Union[list[Token], ExpressionTreeNode]
    code: list[tuple[CodeStatement, ...]]


# name "string" expression!
@dataclass
class AfterStatement(CodeStatement, CodeStatementKeywordable):
    keyword: Token
    expression: Union[list[Token], ExpressionTreeNode]
    code: list[tuple[CodeStatement, ...]]


# name name (, name)* name string!
@dataclass
class ExportStatement(CodeStatement, CodeStatementDebuggable):
    export_keyword: Token
    names: list[Token]
    to_keyword: Token
    target_file: Token
    debug: int

    # Compatibility init for legacy tests

    def __init__(
        self,
        export_keyword=None,
        names=None,
        to_keyword=None,
        target_file=None,
        debug=0,
    ):
        self.export_keyword = export_keyword
        self.names = names or []
        self.to_keyword = to_keyword
        self.target_file = target_file
        self.debug = debug


# name
@dataclass
class ImportStatement(CodeStatement, CodeStatementKeywordable, CodeStatementDebuggable):
    keyword: Token
    names: list[Token]
    from_keyword: Optional[Token]
    source_file: Optional[Token]
    debug: int

    # Compatibility init for legacy tests

    def __init__(self, keyword=None, names=None, from_keyword=None, source_file=None, debug=0):
        self.keyword = keyword
        self.names = names or []
        self.from_keyword = from_keyword
        self.source_file = source_file
        self.debug = debug


# idea: create a class that evaluates at runtime what a statement is, so then execute it
def split_into_statements(tokens: list[Token]) -> list[list[Token]]:
    statements: list[list[Token]] = [[]]
    bracket_layers = 0
    square_bracket_layers = 0
    for token in tokens:
        # check for expression-ending newlines
        if (
            token.type == TokenType.WHITESPACE and not statements[-1]
        ):  # don't care about whitespace at the beginning or end of an expression, idk
            continue
        if token.type == TokenType.NEWLINE and not statements[-1] and len(statements) > 1:
            statements[-2].append(token)
        else:
            statements[-1].append(token)

        # Track both curly and square bracket layers
        if token.type == TokenType.L_CURLY:
            bracket_layers += 1
        elif token.type == TokenType.R_CURLY:
            bracket_layers -= 1
        elif token.type == TokenType.L_SQUARE:
            square_bracket_layers += 1
        elif token.type == TokenType.R_SQUARE:
            square_bracket_layers -= 1

        if (token.type in [TokenType.R_CURLY, TokenType.BANG, TokenType.QUESTION]
                and bracket_layers == 0 and square_bracket_layers == 0):
            while statements[-1][-1].type == TokenType.NEWLINE:  # remove newlines at the end of a statement
                statements[-1].pop()
            statements.append([])

    # remove stray newlines cause they are annoying and shit, also remove empty tings
    final_statements = []
    for statement in statements:
        while statement and statement[-1].type in {
            TokenType.WHITESPACE,
            TokenType.NEWLINE,
        }:  # NOTE: END WILL NEVER BE WHITESPACE
            statement.pop()
        while statement and statement[0].type in {
            TokenType.WHITESPACE,
            TokenType.NEWLINE,
        }:  # NOTE: NOW START WILL NEVER BE WHITESPACE EITHER
            statement.pop(0)
        if not statement:
            continue
        final_statements.append(statement)

    return final_statements


def extract_type_annotations(
    _filename: str, _code: str, statements: list[list[Token]]
) -> list[tuple[list[Token], Optional[list[Token]]]]:
    """Extract type annotations from statements before they are removed."""
    result = []

    for tokens in statements:
        type_annotation = None
        scope_layers = 0
        square_bracket_layers = 0
        i = 0

        while i < len(tokens):
            t = tokens[i]
            if t.type == TokenType.L_CURLY:
                scope_layers += 1
            elif t.type == TokenType.R_CURLY:
                scope_layers -= 1
            elif t.type == TokenType.L_SQUARE:
                square_bracket_layers += 1
            elif t.type == TokenType.R_SQUARE:
                square_bracket_layers -= 1
            elif t.type == TokenType.COLON and scope_layers == 0 and square_bracket_layers == 0:
                # Found a type annotation - extract everything from here
                # until the equals sign
                type_tokens = []
                i += 1
                while i < len(tokens) and tokens[i].type not in [
                    TokenType.EQUAL,
                    TokenType.L_CURLY,
                ]:
                    if tokens[i].type != TokenType.WHITESPACE:
                        type_tokens.append(tokens[i])
                    i += 1
                if type_tokens:
                    type_annotation = type_tokens
                break
            i += 1

        result.append((tokens, type_annotation))

    return result


def remove_type_hints(filename: str, code: str, statements: list[list[Token]]) -> list[list[Token]]:
    new_statements = []
    for tokens in statements:
        new_tokens = []
        adding_tokens = True
        scope_layers, square_bracket_layers = 0, 0
        ref_square_bracket_layers = 0
        curr = 0

        while curr < len(tokens):
            t = tokens[curr]

            # handle brackets
            if t.type == TokenType.L_CURLY:
                scope_layers += 1
            elif t.type == TokenType.R_CURLY:
                scope_layers -= 1
            if t.type == TokenType.L_SQUARE:
                square_bracket_layers += 1
            elif t.type == TokenType.R_SQUARE:
                square_bracket_layers -= 1

            # must be in the right place to consider removal
            if t.type == TokenType.COLON and scope_layers == 0:
                adding_tokens = False
                ref_square_bracket_layers = square_bracket_layers  # prob gonna be zero but idek imma just do this
            if not adding_tokens:
                # check if it is at an operator
                if STR_TO_OPERATOR.get(t.value) and square_bracket_layers == ref_square_bracket_layers:
                    adding_tokens = True

                # adjust for Name<...> things, which also allows regex to pass too
                elif (
                    t.type == TokenType.NAME and curr + 1 < len(tokens) and tokens[curr + 1].type == TokenType.LESS_THAN
                ):
                    try:
                        while tokens[curr + 1].type != TokenType.GREATER_THAN:
                            curr += 1
                        curr += 1
                    except IndexError:
                        raise_error_at_token(
                            filename,
                            code,
                            "Something went wrong parsing type hints (a.k.a. removing them).",
                            t,
                        )

            if adding_tokens:  # cannot be elif because adding_tokens can be modified in the previous statement
                new_tokens.append(t)

            curr += 1

        new_statements.append(new_tokens)

    return new_statements


def assert_proper_indentation(filename: str, tokens: list[Token], code: str) -> None:
    looking_for_whitespace = False
    for t in tokens:
        if not looking_for_whitespace:
            if t.type == TokenType.NEWLINE:
                looking_for_whitespace = True
        else:
            if t.type == TokenType.WHITESPACE and "\t" in t.value:
                raise_error_at_token(
                    filename,
                    code,
                    "Invalid indentation detected: tabs are not supported.",
                    t,
                )
            if t.type == TokenType.WHITESPACE and len(t.value) % 3:
                raise_error_at_token(
                    filename,
                    code,
                    "Invalid indenting detected (must be a multiple of 3 spaces).",
                    t,
                )
            looking_for_whitespace = False


def create_function_definition(
    filename: str,
    without_whitespace: list[Token],
    code: str,
    statements_inside_scope: list[tuple[CodeStatement, ...]],
) -> tuple[CodeStatement, ...]:
    # Parse function declaration
    # First, collect the initial NAME tokens (keywords and function name)
    names_in_row = []
    i = 0
    while i < len(without_whitespace) and without_whitespace[i].type == TokenType.NAME:
        names_in_row.append(without_whitespace[i])
        i += 1

    if not 2 <= len(names_in_row):
        raise_error_at_token(
            filename,
            code,
            "Insufficient keyword count in function declaration.",
            without_whitespace[0],
        )

    # Check if async
    is_async = len(names_in_row) >= 2 and names_in_row[0].value == "async"
    if is_async:
        keywords = names_in_row[:2]
        name = names_in_row[2] if len(names_in_row) > 2 else None
        initial_args = [t for t in names_in_row[3:] if t.value != ""]
    else:
        keywords = names_in_row[:1]
        name = names_in_row[1] if len(names_in_row) > 1 else None
        initial_args = [t for t in names_in_row[2:] if t.value != ""]

    if name is None:
        raise_error_at_token(
            filename,
            code,
            "Function declaration must have a name.",
            without_whitespace[0],
        )

    # Now collect all remaining parameter names (skipping commas)
    # Note: parentheses are treated as whitespace by the lexer
    args = list(initial_args)
    while i < len(without_whitespace):
        token = without_whitespace[i]
        if token.type == TokenType.NAME and token.value != "":
            args.append(token)
        elif token.type in {TokenType.FUNC_POINT, TokenType.L_CURLY}:
            # Stop when we hit the => or { that starts the function body
            break
        elif token.type != TokenType.COMMA:
            # If we hit something unexpected (not a comma), stop parsing
            break
        i += 1

    return (
        FunctionDefinition(
            keywords=keywords,
            name=name,
            args=args,
            code=statements_inside_scope,
            is_async=is_async,
        ),
    )


def create_scoped_code_statement(
    filename: str,
    tokens: list[Token],
    without_whitespace: list[Token],
    code: str,
    _type_annotation: Optional[list[Token]] = None,
) -> tuple[CodeStatement, ...]:
    # this means that a scope is detected in the statement
    ends_with_punc = tokens[-1].type in {TokenType.BANG, TokenType.QUESTION}
    if tokens[-1 - int(ends_with_punc)].type != TokenType.R_CURLY:  # end will never be whitespace
        raise_error_at_token(
            filename,
            code,
            "End of statement with open scope must close the scope.",
            tokens[-1],
        )
    if without_whitespace[0].type != TokenType.NAME:
        raise_error_at_token(
            filename,
            code,
            "Scoped code statement must start with a keyword.",
            without_whitespace[0],
        )

    # at this point, can be when, class dec, function call, or if statement
    scope_open_index = [t.type == TokenType.L_CURLY for t in tokens].index(True)
    stuff_inside_scope = tokens[scope_open_index + 1 : len(tokens) - ends_with_punc - 1]
    statements_inside_scope = generate_syntax_tree(filename, stuff_inside_scope, code)

    # see the function pointer -> immediately know
    can_be_function = any(
        [t.type == TokenType.FUNC_POINT for i, t in enumerate(without_whitespace) if i < scope_open_index]
    )

    # now finally, check for classes
    can_be_class = (
        without_whitespace[0].type == TokenType.NAME
        and without_whitespace[1].type == TokenType.NAME
        and without_whitespace[2].type == TokenType.L_CURLY
    )

    # check for function block
    can_be_function_block = (
        len(without_whitespace) >= 2
        and without_whitespace[0].type == TokenType.NAME
        and without_whitespace[1].type == TokenType.NAME
        and (
            (without_whitespace[0].value == "function")
            or (
                len(without_whitespace) >= 3
                and without_whitespace[0].value == "async"
                and without_whitespace[1].value == "function"
            )
        )
    )

    # finally, check for after/when statement -- identical syntax to conditional
    # so no point doing anything extra special

    # this dude is separated to another function because the same code is reused in () => ... functions (no scope)
    possibilities: list[CodeStatement] = []
    if can_be_function:
        return create_function_definition(filename, without_whitespace, code, statements_inside_scope)

    if can_be_function_block:
        return create_function_definition(filename, without_whitespace, code, statements_inside_scope)

    if can_be_class:
        # build thing for the class statement
        possibilities.append(
            ClassDeclaration(
                keyword=without_whitespace[0],
                name=without_whitespace[1],
                code=statements_inside_scope,
            )
        )

    possibilities.extend(
        [
            Conditional(
                keyword=without_whitespace[0],
                expression=tokens[int(tokens[0].type == TokenType.WHITESPACE) + 1 : scope_open_index],
                code=statements_inside_scope,
            ),
            AfterStatement(
                keyword=without_whitespace[0],
                expression=tokens[int(tokens[0].type == TokenType.WHITESPACE) + 1 : scope_open_index],
                code=statements_inside_scope,
            ),
            WhenStatement(
                keyword=without_whitespace[0],
                expression=tokens[int(tokens[0].type == TokenType.WHITESPACE) + 1 : scope_open_index],
                code=statements_inside_scope,
            ),
        ]
    )
    return tuple(possibilities)


def is_proper_comma_list(
    without_whitespace: list[Token],
    accepted_tokens: frozenset[TokenType] = frozenset({TokenType.NAME}),
) -> bool:
    looking_for_comma = without_whitespace[0].type != TokenType.COMMA
    for t in without_whitespace[1:]:
        if not looking_for_comma and t.type not in accepted_tokens or looking_for_comma and t.type != TokenType.COMMA:
            return False
        looking_for_comma = not looking_for_comma
    return True


def create_unscoped_code_statement(
    filename: str,
    tokens: list[Token],
    without_whitespace: list[Token],
    code: str,
    type_annotation: Optional[list[Token]] = None,
) -> tuple[CodeStatement, ...]:
    """Parse statements without curly braces into AST nodes.

    Handles variable declarations, assignments, imports, exports,
    function definitions, return/delete statements, and satirical keywords.
    """

    is_debug = tokens[-1].type == TokenType.QUESTION
    # Calculate confidence: ! = positive priority, ¡ = negative priority
    if is_debug:
        confidence = 0
    elif tokens[-1].type == TokenType.BANG:
        bang_val = tokens[-1].value
        if "¡" in bang_val:
            confidence = -len(bang_val)  # negative priority
        else:
            confidence = len(bang_val)  # positive priority
    else:
        confidence = 0
    debug_level = 0 if not is_debug else len(tokens[-1].value)

    tokens_no_ws = [t for t in tokens if t.type != TokenType.WHITESPACE]

    # it's a function!!!!!!!!!!!!!!!!!
    has_func_point = [t.type == TokenType.FUNC_POINT for t in tokens]
    if any(has_func_point):
        func_point_index = has_func_point.index(True)
        return create_function_definition(
            filename,
            without_whitespace,
            code,
            [
                (
                    ReturnStatement(
                        keyword=None,
                        expression=tokens[func_point_index + 1 : -1],
                        debug=debug_level,
                    ),
                )
            ],
        )

    # import statement (legacy): import name, name, name!
    can_be_import_legacy = (
        all(t.type in {TokenType.NAME, TokenType.COMMA} for t in without_whitespace[:-1])
        and len(without_whitespace) >= 3
        and is_proper_comma_list(without_whitespace[1:-1])
        and without_whitespace[0].type == TokenType.NAME
        and without_whitespace[1].type == TokenType.NAME
    )

    # import statement (spec): import name, name from source!
    can_be_import_from = False
    import_from_idx = -1
    if len(without_whitespace) >= 5 and without_whitespace[0].type == TokenType.NAME:
        from_indices = [
            i
            for i, tok in enumerate(without_whitespace[1:-1], start=1)
            if tok.type == TokenType.NAME and tok.value == "from"
        ]
        if len(from_indices) == 1:
            import_from_idx = from_indices[0]
            name_tokens = without_whitespace[1:import_from_idx]
            can_be_import_from = (
                bool(name_tokens)
                and all(t.type in {TokenType.NAME, TokenType.COMMA} for t in name_tokens)
                and is_proper_comma_list(name_tokens)
                and import_from_idx + 2 == len(without_whitespace) - 1
                and without_whitespace[import_from_idx + 1].type in {TokenType.NAME, TokenType.STRING}
            )

    # -- Compound assignment desugaring (+=, -=, *=, /=, ^=) --
    # Desugar ``name OP= expr!`` into a VariableAssignment where the
    # expression is ``name OP expr``.
    compound_token_idx = next(
        (i for i, t in enumerate(tokens) if t.type == TokenType.COMPOUND_ASSIGN), -1
    )
    if compound_token_idx != -1:
        compound_tok = tokens[compound_token_idx]
        # Map compound operator value to the bare-operator token type
        _COMPOUND_TO_OP: dict[str, TokenType] = {
            "+=": TokenType.ADD,
            "-=": TokenType.SUBTRACT,
            "*=": TokenType.MULTIPLY,
            "/=": TokenType.DIVIDE,
            "^=": TokenType.CARROT,
        }
        op_type = _COMPOUND_TO_OP[compound_tok.value]
        op_char = compound_tok.value[0]
        name_tok = without_whitespace[0]
        # Build synthetic expression tokens: <name> <SPACE> <OP> <SPACE> <rhs_tokens...>
        rhs_tokens = tokens[compound_token_idx + 1 : -1]  # everything between OP= and terminator
        synthetic_expr: list[Token] = [
            Token(TokenType.NAME, name_tok.value, name_tok.line, name_tok.col),
            Token(TokenType.WHITESPACE, " ", compound_tok.line, compound_tok.col),
            Token(op_type, op_char, compound_tok.line, compound_tok.col),
        ] + rhs_tokens
        return (
            VariableAssignment(
                name=name_tok,
                expression=synthetic_expr,
                debug=debug_level,
                indexes=[],
                confidence=confidence,
            ),
        )

    # export statement: export name, name, name to string/name!
    can_be_export = (
        all(t.type in {TokenType.STRING, TokenType.NAME, TokenType.COMMA} for t in without_whitespace[:-1])
        and len(without_whitespace) >= 5
        and is_proper_comma_list(without_whitespace[1:-3])
        and without_whitespace[0].type == TokenType.NAME
        and without_whitespace[1].type == TokenType.NAME
        and without_whitespace[-2].type in {TokenType.NAME, TokenType.STRING}
        and without_whitespace[-3].type == TokenType.NAME
    )

    # let's see what can be what D:
    can_be_return = without_whitespace[0].type == TokenType.NAME
    can_be_delete = (
        can_be_return
        and len(without_whitespace) == 3
        and without_whitespace[1].type == TokenType.NAME
        and without_whitespace[2].type in {TokenType.BANG, TokenType.QUESTION}
    )

    contains_equals = any(tokens_is_equal := [t.type == TokenType.EQUAL and t.value == "=" for t in tokens])
    can_be_var_assignment = can_be_var_declaration = contains_equals

    # checking for single name and index for variable assignment
    can_be_var_assignment &= (
        len(without_whitespace) >= 4
        and without_whitespace[0].type == TokenType.NAME
        and without_whitespace[1].type in {TokenType.EQUAL, TokenType.L_SQUARE}
    )
    var_assignment_index: list[list[Token]] = [[]]  # is list[list] to handle multiple indexes
    bracket_layers, add_to_var_assignment_index = 0, False
    for t in tokens:
        if not can_be_var_assignment:
            break

        if t.type == TokenType.L_SQUARE:
            if bracket_layers == 0:
                add_to_var_assignment_index = True
            bracket_layers += 1
            continue
        elif t.type == TokenType.R_SQUARE:
            bracket_layers -= 1
            if bracket_layers == 0:
                add_to_var_assignment_index = False
                var_assignment_index.append([])
            continue
        elif bracket_layers == 0 and t.type == TokenType.EQUAL:  # exit when hitting the equals
            break

        if add_to_var_assignment_index:
            var_assignment_index[-1].append(t)
    var_assignment_index.pop()  # the last one will always be empty

    # checking modifiers and lifetime for varianle declaration
    names_in_row: list[Token] = []
    looking_for_lifetime, lifetime = False, None
    lifetime_parts: list[str] = []
    destructure_names: Optional[list[Token]] = None
    for t in without_whitespace:
        if (
            not can_be_var_declaration or can_be_var_assignment
        ):  # var assignment has a single name, therefore counteracts being decl
            break
        if not looking_for_lifetime:
            if t.type != TokenType.NAME:
                if t.type == TokenType.LESS_THAN:
                    looking_for_lifetime = True
                    lifetime_parts = []
                    continue
                elif t.type == TokenType.L_SQUARE and len(names_in_row) >= 2:
                    # Destructuring pattern: const var [a, b] = expr!
                    idx = without_whitespace.index(t)
                    destructure_names = []
                    j = idx + 1
                    while j < len(without_whitespace) and without_whitespace[j].type != TokenType.R_SQUARE:
                        if without_whitespace[j].type == TokenType.NAME:
                            destructure_names.append(without_whitespace[j])
                        j += 1
                    if destructure_names:
                        # Use first destructured name as the primary name
                        names_in_row.append(destructure_names[0])
                    break
                else:
                    break
            if t.value == "~":
                break
            names_in_row.append(t)
        else:
            if t.type == TokenType.GREATER_THAN or not 2 <= len(names_in_row) <= 4 or not can_be_var_declaration:
                # Combine all parts into lifetime string
                if lifetime_parts and not lifetime:
                    lifetime = "<" + "".join(lifetime_parts) + ">"
                break
            lifetime_parts.append(t.value)

    can_be_var_declaration &= 2 <= len(names_in_row) <= 4

    declaration_confidence = confidence
    if can_be_var_declaration:
        eq_idx_no_ws = next(
            (i for i, tok in enumerate(without_whitespace) if tok.type == TokenType.EQUAL and tok.value == "="),
            -1,
        )
        if eq_idx_no_ws >= 3:
            marker = without_whitespace[eq_idx_no_ws - 3:eq_idx_no_ws]
            if (
                marker[0].type == TokenType.NAME
                and marker[0].value == "~"
                and marker[1].type == TokenType.NAME
                and marker[2].type == TokenType.NAME
                and marker[2].value == "~"
            ):
                try:
                    declaration_confidence = int(float(marker[1].value))
                except ValueError:
                    raise_error_at_token(
                        filename,
                        code,
                        "Invalid confidence marker. Expected syntax like ~80~.",
                        marker[1],
                    )

    # make a list of all possible things, starting with plain expression
    possibilities: list[CodeStatement] = [ExpressionStatement(tokens[:-1], debug_level)]
    # Consider ReverseStatement as a possibility (do not short-circuit)
    if (
        len(tokens_no_ws) == 3
        and tokens_no_ws[0].type == TokenType.NAME
        and tokens_no_ws[1].type == TokenType.NAME
        and tokens_no_ws[2].type in {TokenType.BANG, TokenType.QUESTION}
    ):
        possibilities.append(
            ReverseStatement(
                keyword=tokens_no_ws[0],  # candidate keyword (should resolve to 'reverse')
                name=tokens_no_ws[1],
                debug=debug_level,
            )
        )
    # Also accept standalone 'reverse!' (2 tokens: keyword + bang)
    if (
        len(tokens_no_ws) == 2
        and tokens_no_ws[0].type == TokenType.NAME
        and tokens_no_ws[1].type in {TokenType.BANG, TokenType.QUESTION}
    ):
        possibilities.append(
            ReverseStatement(
                keyword=tokens_no_ws[0],
                name=tokens_no_ws[0],  # name same as keyword (dummy)
                debug=debug_level,
            )
        )
    if can_be_return:
        possibilities.append(
            ReturnStatement(
                keyword=without_whitespace[0],  # should be the same as tokens[0].value but this makes me feel safe
                expression=tokens[1:-1],
                debug=debug_level,
            )
        )
    if can_be_delete:
        possibilities.append(
            DeleteStatement(
                keyword=without_whitespace[0],
                name=without_whitespace[1],
                debug=debug_level,
            )
        )
    if can_be_import_from:
        possibilities.append(
            ImportStatement(
                keyword=without_whitespace[0],
                names=[t for t in without_whitespace[1:import_from_idx] if t.type == TokenType.NAME],
                from_keyword=without_whitespace[import_from_idx],
                source_file=without_whitespace[import_from_idx + 1],
                debug=debug_level,
            )
        )
    elif can_be_import_legacy:
        possibilities.append(
            ImportStatement(
                keyword=without_whitespace[0],
                names=[t for t in without_whitespace[1:-1] if t.type == TokenType.NAME],
                from_keyword=None,
                source_file=None,
                debug=debug_level,
            )
        )
    if can_be_export:
        possibilities.append(
            ExportStatement(
                export_keyword=without_whitespace[0],
                names=[t for t in without_whitespace[1:-3] if t.type == TokenType.NAME],
                to_keyword=without_whitespace[-3],
                target_file=without_whitespace[-2],
                debug=debug_level,
            )
        )
    if can_be_var_declaration:
        possibilities.append(
            VariableDeclaration(
                name=names_in_row[-1],
                modifiers=names_in_row[:-1],
                lifetime=lifetime,
                expression=tokens[tokens_is_equal.index(True) + 1 : -1],  # the end should be a puncutation
                confidence=declaration_confidence,
                debug=debug_level,
                type_annotation=type_annotation,
                destructure_names=destructure_names,
            )
        )
    if can_be_var_assignment:
        possibilities.append(
            VariableAssignment(
                name=without_whitespace[0],
                expression=tokens[tokens_is_equal.index(True) + 1 : -1],
                debug=debug_level,
                indexes=var_assignment_index,
                confidence=confidence,
            )
        )
    return tuple(possibilities)


def generate_syntax_tree(filename: str, tokens: list[Token], code: str) -> list[tuple[CodeStatement, ...]]:
    """Split the code up into lines, which are then parsed and shit"""

    assert_proper_indentation(filename, tokens, code)
    statements = split_into_statements(tokens)
    extracted_types = extract_type_annotations(filename, code, statements)
    removed_hints = remove_type_hints(filename, code, [tokens for tokens, _ in extracted_types])
    final_statements = []

    # now we need to perform pattern matching on each list of statements
    for (_, type_annotation), tokens in zip(  # pylint: disable=unused-variable
        extracted_types, removed_hints
    ):
        without_whitespace = [t for t in tokens if t.type != TokenType.WHITESPACE]

        if without_whitespace and without_whitespace[-1].type not in {
            TokenType.BANG,
            TokenType.QUESTION,
            TokenType.R_CURLY,
        }:
            raise_error_at_line(
                filename,
                code,
                without_whitespace[-1].line,
                "Every statement must end with !, !!, !!!, or ?",
            )

        try:
            # contains an open scope :)
            if any(t.type == TokenType.L_CURLY for t in tokens):
                final_statements.append(
                    create_scoped_code_statement(filename, tokens, without_whitespace, code, type_annotation)
                )

            else:
                final_statements.append(
                    create_unscoped_code_statement(
                        filename,
                        tokens,
                        without_whitespace,
                        code,
                        type_annotation,
                    )
                )

            # exit if some possiblity was found
            if final_statements[-1]:
                continue
        except IndexError:  # i have no idea what kind of errors are going to be rasied here
            pass
        raise_error_at_line(
            filename,
            code,
            without_whitespace[0].line,
            "Error parsing statement. I have no idea what went wrong, double check it and try again.",
        )

    return final_statements
